package org.pay.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Check_acc_file_detail implements Serializable {
    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : ID
     */
    private String ID;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHECK_DT
     */
    private String CHECK_DT;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_NO
     */
    private String CHAN_NO;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHECK_STATE
     */
    private Integer CHECK_STATE;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_LOG_NO
     */
    private String CHAN_LOG_NO;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_TXN_TYPE
     */
    private Integer CHAN_TXN_TYPE;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_TXN_AMT
     */
    private BigDecimal CHAN_TXN_AMT;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_TXN_BAL
     */
    private Long CHAN_TXN_BAL;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_TXN_DEAMT
     */
    private BigDecimal CHAN_TXN_DEAMT;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_STL_DT
     */
    private String CHAN_STL_DT;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_STL_TM
     */
    private Date CHAN_STL_TM;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_TXN_CD
     */
    private String CHAN_TXN_CD;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : LOG_NO
     */
    private String LOG_NO;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : RMARK
     */
    private String RMARK;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_GUEST_BAL
     */
    private Long CHAN_GUEST_BAL;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_TXN_GT_XA
     */
    private Long CHAN_TXN_GT_XA;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_TXN_GT_TX
     */
    private Long CHAN_TXN_GT_TX;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_TXN_GT_HX
     */
    private Long CHAN_TXN_GT_HX;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_TXN_GT_RX
     */
    private Long CHAN_TXN_GT_RX;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_TXN_GT_BA
     */
    private Long CHAN_TXN_GT_BA;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_TXN_GT_GP
     */
    private Long CHAN_TXN_GT_GP;

    /**
     * 表 : IECPAY.CHECK_ACC_FILE_DETAIL
     * 对应字段 : CHAN_TXN_GT_PN
     */
    private Long CHAN_TXN_GT_PN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IECPAY.CHECK_ACC_FILE_DETAIL
     *
     * @MBG Generated Mon May 15 19:01:43 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.ID：null
     */
    public String getID() {
        return ID;
    }

    /**
     * set method 
     *
     * @param ID  null
     */
    public void setID(String ID) {
        this.ID = ID == null ? null : ID.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHECK_DT：null
     */
    public String getCHECK_DT() {
        return CHECK_DT;
    }

    /**
     * set method 
     *
     * @param CHECK_DT  null
     */
    public void setCHECK_DT(String CHECK_DT) {
        this.CHECK_DT = CHECK_DT == null ? null : CHECK_DT.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_NO：null
     */
    public String getCHAN_NO() {
        return CHAN_NO;
    }

    /**
     * set method 
     *
     * @param CHAN_NO  null
     */
    public void setCHAN_NO(String CHAN_NO) {
        this.CHAN_NO = CHAN_NO == null ? null : CHAN_NO.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHECK_STATE：null
     */
    public Integer getCHECK_STATE() {
        return CHECK_STATE;
    }

    /**
     * set method 
     *
     * @param CHECK_STATE  null
     */
    public void setCHECK_STATE(Integer CHECK_STATE) {
        this.CHECK_STATE = CHECK_STATE;
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_LOG_NO：null
     */
    public String getCHAN_LOG_NO() {
        return CHAN_LOG_NO;
    }

    /**
     * set method 
     *
     * @param CHAN_LOG_NO  null
     */
    public void setCHAN_LOG_NO(String CHAN_LOG_NO) {
        this.CHAN_LOG_NO = CHAN_LOG_NO == null ? null : CHAN_LOG_NO.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_TXN_TYPE：null
     */
    public Integer getCHAN_TXN_TYPE() {
        return CHAN_TXN_TYPE;
    }

    /**
     * set method 
     *
     * @param CHAN_TXN_TYPE  null
     */
    public void setCHAN_TXN_TYPE(Integer CHAN_TXN_TYPE) {
        this.CHAN_TXN_TYPE = CHAN_TXN_TYPE;
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_TXN_AMT：null
     */
    public BigDecimal getCHAN_TXN_AMT() {
        return CHAN_TXN_AMT;
    }

    /**
     * set method 
     *
     * @param CHAN_TXN_AMT  null
     */
    public void setCHAN_TXN_AMT(BigDecimal CHAN_TXN_AMT) {
        this.CHAN_TXN_AMT = CHAN_TXN_AMT;
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_TXN_BAL：null
     */
    public Long getCHAN_TXN_BAL() {
        return CHAN_TXN_BAL;
    }

    /**
     * set method 
     *
     * @param CHAN_TXN_BAL  null
     */
    public void setCHAN_TXN_BAL(Long CHAN_TXN_BAL) {
        this.CHAN_TXN_BAL = CHAN_TXN_BAL;
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_TXN_DEAMT：null
     */
    public BigDecimal getCHAN_TXN_DEAMT() {
        return CHAN_TXN_DEAMT;
    }

    /**
     * set method 
     *
     * @param CHAN_TXN_DEAMT  null
     */
    public void setCHAN_TXN_DEAMT(BigDecimal CHAN_TXN_DEAMT) {
        this.CHAN_TXN_DEAMT = CHAN_TXN_DEAMT;
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_STL_DT：null
     */
    public String getCHAN_STL_DT() {
        return CHAN_STL_DT;
    }

    /**
     * set method 
     *
     * @param CHAN_STL_DT  null
     */
    public void setCHAN_STL_DT(String CHAN_STL_DT) {
        this.CHAN_STL_DT = CHAN_STL_DT == null ? null : CHAN_STL_DT.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_STL_TM：null
     */
    public Date getCHAN_STL_TM() {
        return CHAN_STL_TM;
    }

    /**
     * set method 
     *
     * @param CHAN_STL_TM  null
     */
    public void setCHAN_STL_TM(Date CHAN_STL_TM) {
        this.CHAN_STL_TM = CHAN_STL_TM;
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_TXN_CD：null
     */
    public String getCHAN_TXN_CD() {
        return CHAN_TXN_CD;
    }

    /**
     * set method 
     *
     * @param CHAN_TXN_CD  null
     */
    public void setCHAN_TXN_CD(String CHAN_TXN_CD) {
        this.CHAN_TXN_CD = CHAN_TXN_CD == null ? null : CHAN_TXN_CD.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.LOG_NO：null
     */
    public String getLOG_NO() {
        return LOG_NO;
    }

    /**
     * set method 
     *
     * @param LOG_NO  null
     */
    public void setLOG_NO(String LOG_NO) {
        this.LOG_NO = LOG_NO == null ? null : LOG_NO.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.RMARK：null
     */
    public String getRMARK() {
        return RMARK;
    }

    /**
     * set method 
     *
     * @param RMARK  null
     */
    public void setRMARK(String RMARK) {
        this.RMARK = RMARK == null ? null : RMARK.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_GUEST_BAL：null
     */
    public Long getCHAN_GUEST_BAL() {
        return CHAN_GUEST_BAL;
    }

    /**
     * set method 
     *
     * @param CHAN_GUEST_BAL  null
     */
    public void setCHAN_GUEST_BAL(Long CHAN_GUEST_BAL) {
        this.CHAN_GUEST_BAL = CHAN_GUEST_BAL;
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_TXN_GT_XA：null
     */
    public Long getCHAN_TXN_GT_XA() {
        return CHAN_TXN_GT_XA;
    }

    /**
     * set method 
     *
     * @param CHAN_TXN_GT_XA  null
     */
    public void setCHAN_TXN_GT_XA(Long CHAN_TXN_GT_XA) {
        this.CHAN_TXN_GT_XA = CHAN_TXN_GT_XA;
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_TXN_GT_TX：null
     */
    public Long getCHAN_TXN_GT_TX() {
        return CHAN_TXN_GT_TX;
    }

    /**
     * set method 
     *
     * @param CHAN_TXN_GT_TX  null
     */
    public void setCHAN_TXN_GT_TX(Long CHAN_TXN_GT_TX) {
        this.CHAN_TXN_GT_TX = CHAN_TXN_GT_TX;
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_TXN_GT_HX：null
     */
    public Long getCHAN_TXN_GT_HX() {
        return CHAN_TXN_GT_HX;
    }

    /**
     * set method 
     *
     * @param CHAN_TXN_GT_HX  null
     */
    public void setCHAN_TXN_GT_HX(Long CHAN_TXN_GT_HX) {
        this.CHAN_TXN_GT_HX = CHAN_TXN_GT_HX;
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_TXN_GT_RX：null
     */
    public Long getCHAN_TXN_GT_RX() {
        return CHAN_TXN_GT_RX;
    }

    /**
     * set method 
     *
     * @param CHAN_TXN_GT_RX  null
     */
    public void setCHAN_TXN_GT_RX(Long CHAN_TXN_GT_RX) {
        this.CHAN_TXN_GT_RX = CHAN_TXN_GT_RX;
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_TXN_GT_BA：null
     */
    public Long getCHAN_TXN_GT_BA() {
        return CHAN_TXN_GT_BA;
    }

    /**
     * set method 
     *
     * @param CHAN_TXN_GT_BA  null
     */
    public void setCHAN_TXN_GT_BA(Long CHAN_TXN_GT_BA) {
        this.CHAN_TXN_GT_BA = CHAN_TXN_GT_BA;
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_TXN_GT_GP：null
     */
    public Long getCHAN_TXN_GT_GP() {
        return CHAN_TXN_GT_GP;
    }

    /**
     * set method 
     *
     * @param CHAN_TXN_GT_GP  null
     */
    public void setCHAN_TXN_GT_GP(Long CHAN_TXN_GT_GP) {
        this.CHAN_TXN_GT_GP = CHAN_TXN_GT_GP;
    }

    /**
     * get method 
     *
     * @return IECPAY.CHECK_ACC_FILE_DETAIL.CHAN_TXN_GT_PN：null
     */
    public Long getCHAN_TXN_GT_PN() {
        return CHAN_TXN_GT_PN;
    }

    /**
     * set method 
     *
     * @param CHAN_TXN_GT_PN  null
     */
    public void setCHAN_TXN_GT_PN(Long CHAN_TXN_GT_PN) {
        this.CHAN_TXN_GT_PN = CHAN_TXN_GT_PN;
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Check_acc_file_detail other = (Check_acc_file_detail) that;
        return (this.getID() == null ? other.getID() == null : this.getID().equals(other.getID()))
            && (this.getCHECK_DT() == null ? other.getCHECK_DT() == null : this.getCHECK_DT().equals(other.getCHECK_DT()))
            && (this.getCHAN_NO() == null ? other.getCHAN_NO() == null : this.getCHAN_NO().equals(other.getCHAN_NO()))
            && (this.getCHECK_STATE() == null ? other.getCHECK_STATE() == null : this.getCHECK_STATE().equals(other.getCHECK_STATE()))
            && (this.getCHAN_LOG_NO() == null ? other.getCHAN_LOG_NO() == null : this.getCHAN_LOG_NO().equals(other.getCHAN_LOG_NO()))
            && (this.getCHAN_TXN_TYPE() == null ? other.getCHAN_TXN_TYPE() == null : this.getCHAN_TXN_TYPE().equals(other.getCHAN_TXN_TYPE()))
            && (this.getCHAN_TXN_AMT() == null ? other.getCHAN_TXN_AMT() == null : this.getCHAN_TXN_AMT().equals(other.getCHAN_TXN_AMT()))
            && (this.getCHAN_TXN_BAL() == null ? other.getCHAN_TXN_BAL() == null : this.getCHAN_TXN_BAL().equals(other.getCHAN_TXN_BAL()))
            && (this.getCHAN_TXN_DEAMT() == null ? other.getCHAN_TXN_DEAMT() == null : this.getCHAN_TXN_DEAMT().equals(other.getCHAN_TXN_DEAMT()))
            && (this.getCHAN_STL_DT() == null ? other.getCHAN_STL_DT() == null : this.getCHAN_STL_DT().equals(other.getCHAN_STL_DT()))
            && (this.getCHAN_STL_TM() == null ? other.getCHAN_STL_TM() == null : this.getCHAN_STL_TM().equals(other.getCHAN_STL_TM()))
            && (this.getCHAN_TXN_CD() == null ? other.getCHAN_TXN_CD() == null : this.getCHAN_TXN_CD().equals(other.getCHAN_TXN_CD()))
            && (this.getLOG_NO() == null ? other.getLOG_NO() == null : this.getLOG_NO().equals(other.getLOG_NO()))
            && (this.getRMARK() == null ? other.getRMARK() == null : this.getRMARK().equals(other.getRMARK()))
            && (this.getCHAN_GUEST_BAL() == null ? other.getCHAN_GUEST_BAL() == null : this.getCHAN_GUEST_BAL().equals(other.getCHAN_GUEST_BAL()))
            && (this.getCHAN_TXN_GT_XA() == null ? other.getCHAN_TXN_GT_XA() == null : this.getCHAN_TXN_GT_XA().equals(other.getCHAN_TXN_GT_XA()))
            && (this.getCHAN_TXN_GT_TX() == null ? other.getCHAN_TXN_GT_TX() == null : this.getCHAN_TXN_GT_TX().equals(other.getCHAN_TXN_GT_TX()))
            && (this.getCHAN_TXN_GT_HX() == null ? other.getCHAN_TXN_GT_HX() == null : this.getCHAN_TXN_GT_HX().equals(other.getCHAN_TXN_GT_HX()))
            && (this.getCHAN_TXN_GT_RX() == null ? other.getCHAN_TXN_GT_RX() == null : this.getCHAN_TXN_GT_RX().equals(other.getCHAN_TXN_GT_RX()))
            && (this.getCHAN_TXN_GT_BA() == null ? other.getCHAN_TXN_GT_BA() == null : this.getCHAN_TXN_GT_BA().equals(other.getCHAN_TXN_GT_BA()))
            && (this.getCHAN_TXN_GT_GP() == null ? other.getCHAN_TXN_GT_GP() == null : this.getCHAN_TXN_GT_GP().equals(other.getCHAN_TXN_GT_GP()))
            && (this.getCHAN_TXN_GT_PN() == null ? other.getCHAN_TXN_GT_PN() == null : this.getCHAN_TXN_GT_PN().equals(other.getCHAN_TXN_GT_PN()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getID() == null) ? 0 : getID().hashCode());
        result = prime * result + ((getCHECK_DT() == null) ? 0 : getCHECK_DT().hashCode());
        result = prime * result + ((getCHAN_NO() == null) ? 0 : getCHAN_NO().hashCode());
        result = prime * result + ((getCHECK_STATE() == null) ? 0 : getCHECK_STATE().hashCode());
        result = prime * result + ((getCHAN_LOG_NO() == null) ? 0 : getCHAN_LOG_NO().hashCode());
        result = prime * result + ((getCHAN_TXN_TYPE() == null) ? 0 : getCHAN_TXN_TYPE().hashCode());
        result = prime * result + ((getCHAN_TXN_AMT() == null) ? 0 : getCHAN_TXN_AMT().hashCode());
        result = prime * result + ((getCHAN_TXN_BAL() == null) ? 0 : getCHAN_TXN_BAL().hashCode());
        result = prime * result + ((getCHAN_TXN_DEAMT() == null) ? 0 : getCHAN_TXN_DEAMT().hashCode());
        result = prime * result + ((getCHAN_STL_DT() == null) ? 0 : getCHAN_STL_DT().hashCode());
        result = prime * result + ((getCHAN_STL_TM() == null) ? 0 : getCHAN_STL_TM().hashCode());
        result = prime * result + ((getCHAN_TXN_CD() == null) ? 0 : getCHAN_TXN_CD().hashCode());
        result = prime * result + ((getLOG_NO() == null) ? 0 : getLOG_NO().hashCode());
        result = prime * result + ((getRMARK() == null) ? 0 : getRMARK().hashCode());
        result = prime * result + ((getCHAN_GUEST_BAL() == null) ? 0 : getCHAN_GUEST_BAL().hashCode());
        result = prime * result + ((getCHAN_TXN_GT_XA() == null) ? 0 : getCHAN_TXN_GT_XA().hashCode());
        result = prime * result + ((getCHAN_TXN_GT_TX() == null) ? 0 : getCHAN_TXN_GT_TX().hashCode());
        result = prime * result + ((getCHAN_TXN_GT_HX() == null) ? 0 : getCHAN_TXN_GT_HX().hashCode());
        result = prime * result + ((getCHAN_TXN_GT_RX() == null) ? 0 : getCHAN_TXN_GT_RX().hashCode());
        result = prime * result + ((getCHAN_TXN_GT_BA() == null) ? 0 : getCHAN_TXN_GT_BA().hashCode());
        result = prime * result + ((getCHAN_TXN_GT_GP() == null) ? 0 : getCHAN_TXN_GT_GP().hashCode());
        result = prime * result + ((getCHAN_TXN_GT_PN() == null) ? 0 : getCHAN_TXN_GT_PN().hashCode());
        return result;
    }
}