package org.pay.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Ip_refund_order implements Serializable {
    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : ORDER_ID
     */
    private String ORDER_ID;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : AC_DT
     */
    private String AC_DT;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : AC_TM
     */
    private Date AC_TM;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : ORN_ORDER_ID
     */
    private String ORN_ORDER_ID;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : MERC_ID
     */
    private String MERC_ID;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : MERC_NAME
     */
    private String MERC_NAME;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : REFUND_AMT
     */
    private BigDecimal REFUND_AMT;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : REFUNDP_ROCESS
     */
    private String REFUNDP_ROCESS;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : CHECK_STATE
     */
    private Integer CHECK_STATE;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : CHECK_DT
     */
    private String CHECK_DT;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : PAY_LOG_NO
     */
    private String PAY_LOG_NO;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : OPERATOR_ID
     */
    private String OPERATOR_ID;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : OPERATOR_NAME
     */
    private String OPERATOR_NAME;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : OPERATOR_TIME
     */
    private Date OPERATOR_TIME;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : MEMBER_ID
     */
    private String MEMBER_ID;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : MEMBER_NAME
     */
    private String MEMBER_NAME;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : REQUEST_TIME
     */
    private Date REQUEST_TIME;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : REMARK
     */
    private String REMARK;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : GENERAL_INTEGRAL
     */
    private Long GENERAL_INTEGRAL;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : GENERAL_INTEGRAL_AMT
     */
    private BigDecimal GENERAL_INTEGRAL_AMT;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : PAY_TYPE
     */
    private Integer PAY_TYPE;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : RED_PACKET_AMT
     */
    private BigDecimal RED_PACKET_AMT;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : GUEST_INTEGRAL
     */
    private Long GUEST_INTEGRAL;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : GUEST_INTEGRAL_AMT
     */
    private BigDecimal GUEST_INTEGRAL_AMT;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : TOWN_INTEGRAL_XA
     */
    private Integer TOWN_INTEGRAL_XA;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : TOWN_INTEGRAL_TX_AMT
     */
    private BigDecimal TOWN_INTEGRAL_TX_AMT;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : TOWN_INTEGRAL_HX
     */
    private Integer TOWN_INTEGRAL_HX;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : TOWN_INTEGRAL_XA_AMT
     */
    private BigDecimal TOWN_INTEGRAL_XA_AMT;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : TOWN_INTEGRAL_TX
     */
    private Integer TOWN_INTEGRAL_TX;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : TOWN_INTEGRAL_HX_AMT
     */
    private BigDecimal TOWN_INTEGRAL_HX_AMT;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : TOWN_INTEGRAL_RX
     */
    private Integer TOWN_INTEGRAL_RX;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : TOWN_INTEGRAL_RX_AMT
     */
    private BigDecimal TOWN_INTEGRAL_RX_AMT;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : TOWN_INTEGRAL_BA
     */
    private Integer TOWN_INTEGRAL_BA;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : TOWN_INTEGRAL_BA_AMT
     */
    private BigDecimal TOWN_INTEGRAL_BA_AMT;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : TOWN_INTEGRAL_GP
     */
    private Integer TOWN_INTEGRAL_GP;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : TOWN_INTEGRAL_GP_AMT
     */
    private BigDecimal TOWN_INTEGRAL_GP_AMT;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : TOWN_INTEGRAL_PN
     */
    private Integer TOWN_INTEGRAL_PN;

    /**
     * 表 : IECPAY.IP_REFUND_ORDER
     * 对应字段 : TOWN_INTEGRAL_PN_AMT
     */
    private BigDecimal TOWN_INTEGRAL_PN_AMT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IECPAY.IP_REFUND_ORDER
     *
     * @MBG Generated Mon May 15 19:01:43 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.ORDER_ID：null
     */
    public String getORDER_ID() {
        return ORDER_ID;
    }

    /**
     * set method 
     *
     * @param ORDER_ID  null
     */
    public void setORDER_ID(String ORDER_ID) {
        this.ORDER_ID = ORDER_ID == null ? null : ORDER_ID.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.AC_DT：null
     */
    public String getAC_DT() {
        return AC_DT;
    }

    /**
     * set method 
     *
     * @param AC_DT  null
     */
    public void setAC_DT(String AC_DT) {
        this.AC_DT = AC_DT == null ? null : AC_DT.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.AC_TM：null
     */
    public Date getAC_TM() {
        return AC_TM;
    }

    /**
     * set method 
     *
     * @param AC_TM  null
     */
    public void setAC_TM(Date AC_TM) {
        this.AC_TM = AC_TM;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.ORN_ORDER_ID：null
     */
    public String getORN_ORDER_ID() {
        return ORN_ORDER_ID;
    }

    /**
     * set method 
     *
     * @param ORN_ORDER_ID  null
     */
    public void setORN_ORDER_ID(String ORN_ORDER_ID) {
        this.ORN_ORDER_ID = ORN_ORDER_ID == null ? null : ORN_ORDER_ID.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.MERC_ID：null
     */
    public String getMERC_ID() {
        return MERC_ID;
    }

    /**
     * set method 
     *
     * @param MERC_ID  null
     */
    public void setMERC_ID(String MERC_ID) {
        this.MERC_ID = MERC_ID == null ? null : MERC_ID.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.MERC_NAME：null
     */
    public String getMERC_NAME() {
        return MERC_NAME;
    }

    /**
     * set method 
     *
     * @param MERC_NAME  null
     */
    public void setMERC_NAME(String MERC_NAME) {
        this.MERC_NAME = MERC_NAME == null ? null : MERC_NAME.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.REFUND_AMT：null
     */
    public BigDecimal getREFUND_AMT() {
        return REFUND_AMT;
    }

    /**
     * set method 
     *
     * @param REFUND_AMT  null
     */
    public void setREFUND_AMT(BigDecimal REFUND_AMT) {
        this.REFUND_AMT = REFUND_AMT;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.REFUNDP_ROCESS：null
     */
    public String getREFUNDP_ROCESS() {
        return REFUNDP_ROCESS;
    }

    /**
     * set method 
     *
     * @param REFUNDP_ROCESS  null
     */
    public void setREFUNDP_ROCESS(String REFUNDP_ROCESS) {
        this.REFUNDP_ROCESS = REFUNDP_ROCESS == null ? null : REFUNDP_ROCESS.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.CHECK_STATE：null
     */
    public Integer getCHECK_STATE() {
        return CHECK_STATE;
    }

    /**
     * set method 
     *
     * @param CHECK_STATE  null
     */
    public void setCHECK_STATE(Integer CHECK_STATE) {
        this.CHECK_STATE = CHECK_STATE;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.CHECK_DT：null
     */
    public String getCHECK_DT() {
        return CHECK_DT;
    }

    /**
     * set method 
     *
     * @param CHECK_DT  null
     */
    public void setCHECK_DT(String CHECK_DT) {
        this.CHECK_DT = CHECK_DT == null ? null : CHECK_DT.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.PAY_LOG_NO：null
     */
    public String getPAY_LOG_NO() {
        return PAY_LOG_NO;
    }

    /**
     * set method 
     *
     * @param PAY_LOG_NO  null
     */
    public void setPAY_LOG_NO(String PAY_LOG_NO) {
        this.PAY_LOG_NO = PAY_LOG_NO == null ? null : PAY_LOG_NO.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.OPERATOR_ID：null
     */
    public String getOPERATOR_ID() {
        return OPERATOR_ID;
    }

    /**
     * set method 
     *
     * @param OPERATOR_ID  null
     */
    public void setOPERATOR_ID(String OPERATOR_ID) {
        this.OPERATOR_ID = OPERATOR_ID == null ? null : OPERATOR_ID.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.OPERATOR_NAME：null
     */
    public String getOPERATOR_NAME() {
        return OPERATOR_NAME;
    }

    /**
     * set method 
     *
     * @param OPERATOR_NAME  null
     */
    public void setOPERATOR_NAME(String OPERATOR_NAME) {
        this.OPERATOR_NAME = OPERATOR_NAME == null ? null : OPERATOR_NAME.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.OPERATOR_TIME：null
     */
    public Date getOPERATOR_TIME() {
        return OPERATOR_TIME;
    }

    /**
     * set method 
     *
     * @param OPERATOR_TIME  null
     */
    public void setOPERATOR_TIME(Date OPERATOR_TIME) {
        this.OPERATOR_TIME = OPERATOR_TIME;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.MEMBER_ID：null
     */
    public String getMEMBER_ID() {
        return MEMBER_ID;
    }

    /**
     * set method 
     *
     * @param MEMBER_ID  null
     */
    public void setMEMBER_ID(String MEMBER_ID) {
        this.MEMBER_ID = MEMBER_ID == null ? null : MEMBER_ID.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.MEMBER_NAME：null
     */
    public String getMEMBER_NAME() {
        return MEMBER_NAME;
    }

    /**
     * set method 
     *
     * @param MEMBER_NAME  null
     */
    public void setMEMBER_NAME(String MEMBER_NAME) {
        this.MEMBER_NAME = MEMBER_NAME == null ? null : MEMBER_NAME.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.REQUEST_TIME：null
     */
    public Date getREQUEST_TIME() {
        return REQUEST_TIME;
    }

    /**
     * set method 
     *
     * @param REQUEST_TIME  null
     */
    public void setREQUEST_TIME(Date REQUEST_TIME) {
        this.REQUEST_TIME = REQUEST_TIME;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.REMARK：null
     */
    public String getREMARK() {
        return REMARK;
    }

    /**
     * set method 
     *
     * @param REMARK  null
     */
    public void setREMARK(String REMARK) {
        this.REMARK = REMARK == null ? null : REMARK.trim();
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.GENERAL_INTEGRAL：null
     */
    public Long getGENERAL_INTEGRAL() {
        return GENERAL_INTEGRAL;
    }

    /**
     * set method 
     *
     * @param GENERAL_INTEGRAL  null
     */
    public void setGENERAL_INTEGRAL(Long GENERAL_INTEGRAL) {
        this.GENERAL_INTEGRAL = GENERAL_INTEGRAL;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.GENERAL_INTEGRAL_AMT：null
     */
    public BigDecimal getGENERAL_INTEGRAL_AMT() {
        return GENERAL_INTEGRAL_AMT;
    }

    /**
     * set method 
     *
     * @param GENERAL_INTEGRAL_AMT  null
     */
    public void setGENERAL_INTEGRAL_AMT(BigDecimal GENERAL_INTEGRAL_AMT) {
        this.GENERAL_INTEGRAL_AMT = GENERAL_INTEGRAL_AMT;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.PAY_TYPE：null
     */
    public Integer getPAY_TYPE() {
        return PAY_TYPE;
    }

    /**
     * set method 
     *
     * @param PAY_TYPE  null
     */
    public void setPAY_TYPE(Integer PAY_TYPE) {
        this.PAY_TYPE = PAY_TYPE;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.RED_PACKET_AMT：null
     */
    public BigDecimal getRED_PACKET_AMT() {
        return RED_PACKET_AMT;
    }

    /**
     * set method 
     *
     * @param RED_PACKET_AMT  null
     */
    public void setRED_PACKET_AMT(BigDecimal RED_PACKET_AMT) {
        this.RED_PACKET_AMT = RED_PACKET_AMT;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.GUEST_INTEGRAL：null
     */
    public Long getGUEST_INTEGRAL() {
        return GUEST_INTEGRAL;
    }

    /**
     * set method 
     *
     * @param GUEST_INTEGRAL  null
     */
    public void setGUEST_INTEGRAL(Long GUEST_INTEGRAL) {
        this.GUEST_INTEGRAL = GUEST_INTEGRAL;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.GUEST_INTEGRAL_AMT：null
     */
    public BigDecimal getGUEST_INTEGRAL_AMT() {
        return GUEST_INTEGRAL_AMT;
    }

    /**
     * set method 
     *
     * @param GUEST_INTEGRAL_AMT  null
     */
    public void setGUEST_INTEGRAL_AMT(BigDecimal GUEST_INTEGRAL_AMT) {
        this.GUEST_INTEGRAL_AMT = GUEST_INTEGRAL_AMT;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.TOWN_INTEGRAL_XA：null
     */
    public Integer getTOWN_INTEGRAL_XA() {
        return TOWN_INTEGRAL_XA;
    }

    /**
     * set method 
     *
     * @param TOWN_INTEGRAL_XA  null
     */
    public void setTOWN_INTEGRAL_XA(Integer TOWN_INTEGRAL_XA) {
        this.TOWN_INTEGRAL_XA = TOWN_INTEGRAL_XA;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.TOWN_INTEGRAL_TX_AMT：null
     */
    public BigDecimal getTOWN_INTEGRAL_TX_AMT() {
        return TOWN_INTEGRAL_TX_AMT;
    }

    /**
     * set method 
     *
     * @param TOWN_INTEGRAL_TX_AMT  null
     */
    public void setTOWN_INTEGRAL_TX_AMT(BigDecimal TOWN_INTEGRAL_TX_AMT) {
        this.TOWN_INTEGRAL_TX_AMT = TOWN_INTEGRAL_TX_AMT;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.TOWN_INTEGRAL_HX：null
     */
    public Integer getTOWN_INTEGRAL_HX() {
        return TOWN_INTEGRAL_HX;
    }

    /**
     * set method 
     *
     * @param TOWN_INTEGRAL_HX  null
     */
    public void setTOWN_INTEGRAL_HX(Integer TOWN_INTEGRAL_HX) {
        this.TOWN_INTEGRAL_HX = TOWN_INTEGRAL_HX;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.TOWN_INTEGRAL_XA_AMT：null
     */
    public BigDecimal getTOWN_INTEGRAL_XA_AMT() {
        return TOWN_INTEGRAL_XA_AMT;
    }

    /**
     * set method 
     *
     * @param TOWN_INTEGRAL_XA_AMT  null
     */
    public void setTOWN_INTEGRAL_XA_AMT(BigDecimal TOWN_INTEGRAL_XA_AMT) {
        this.TOWN_INTEGRAL_XA_AMT = TOWN_INTEGRAL_XA_AMT;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.TOWN_INTEGRAL_TX：null
     */
    public Integer getTOWN_INTEGRAL_TX() {
        return TOWN_INTEGRAL_TX;
    }

    /**
     * set method 
     *
     * @param TOWN_INTEGRAL_TX  null
     */
    public void setTOWN_INTEGRAL_TX(Integer TOWN_INTEGRAL_TX) {
        this.TOWN_INTEGRAL_TX = TOWN_INTEGRAL_TX;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.TOWN_INTEGRAL_HX_AMT：null
     */
    public BigDecimal getTOWN_INTEGRAL_HX_AMT() {
        return TOWN_INTEGRAL_HX_AMT;
    }

    /**
     * set method 
     *
     * @param TOWN_INTEGRAL_HX_AMT  null
     */
    public void setTOWN_INTEGRAL_HX_AMT(BigDecimal TOWN_INTEGRAL_HX_AMT) {
        this.TOWN_INTEGRAL_HX_AMT = TOWN_INTEGRAL_HX_AMT;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.TOWN_INTEGRAL_RX：null
     */
    public Integer getTOWN_INTEGRAL_RX() {
        return TOWN_INTEGRAL_RX;
    }

    /**
     * set method 
     *
     * @param TOWN_INTEGRAL_RX  null
     */
    public void setTOWN_INTEGRAL_RX(Integer TOWN_INTEGRAL_RX) {
        this.TOWN_INTEGRAL_RX = TOWN_INTEGRAL_RX;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.TOWN_INTEGRAL_RX_AMT：null
     */
    public BigDecimal getTOWN_INTEGRAL_RX_AMT() {
        return TOWN_INTEGRAL_RX_AMT;
    }

    /**
     * set method 
     *
     * @param TOWN_INTEGRAL_RX_AMT  null
     */
    public void setTOWN_INTEGRAL_RX_AMT(BigDecimal TOWN_INTEGRAL_RX_AMT) {
        this.TOWN_INTEGRAL_RX_AMT = TOWN_INTEGRAL_RX_AMT;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.TOWN_INTEGRAL_BA：null
     */
    public Integer getTOWN_INTEGRAL_BA() {
        return TOWN_INTEGRAL_BA;
    }

    /**
     * set method 
     *
     * @param TOWN_INTEGRAL_BA  null
     */
    public void setTOWN_INTEGRAL_BA(Integer TOWN_INTEGRAL_BA) {
        this.TOWN_INTEGRAL_BA = TOWN_INTEGRAL_BA;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.TOWN_INTEGRAL_BA_AMT：null
     */
    public BigDecimal getTOWN_INTEGRAL_BA_AMT() {
        return TOWN_INTEGRAL_BA_AMT;
    }

    /**
     * set method 
     *
     * @param TOWN_INTEGRAL_BA_AMT  null
     */
    public void setTOWN_INTEGRAL_BA_AMT(BigDecimal TOWN_INTEGRAL_BA_AMT) {
        this.TOWN_INTEGRAL_BA_AMT = TOWN_INTEGRAL_BA_AMT;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.TOWN_INTEGRAL_GP：null
     */
    public Integer getTOWN_INTEGRAL_GP() {
        return TOWN_INTEGRAL_GP;
    }

    /**
     * set method 
     *
     * @param TOWN_INTEGRAL_GP  null
     */
    public void setTOWN_INTEGRAL_GP(Integer TOWN_INTEGRAL_GP) {
        this.TOWN_INTEGRAL_GP = TOWN_INTEGRAL_GP;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.TOWN_INTEGRAL_GP_AMT：null
     */
    public BigDecimal getTOWN_INTEGRAL_GP_AMT() {
        return TOWN_INTEGRAL_GP_AMT;
    }

    /**
     * set method 
     *
     * @param TOWN_INTEGRAL_GP_AMT  null
     */
    public void setTOWN_INTEGRAL_GP_AMT(BigDecimal TOWN_INTEGRAL_GP_AMT) {
        this.TOWN_INTEGRAL_GP_AMT = TOWN_INTEGRAL_GP_AMT;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.TOWN_INTEGRAL_PN：null
     */
    public Integer getTOWN_INTEGRAL_PN() {
        return TOWN_INTEGRAL_PN;
    }

    /**
     * set method 
     *
     * @param TOWN_INTEGRAL_PN  null
     */
    public void setTOWN_INTEGRAL_PN(Integer TOWN_INTEGRAL_PN) {
        this.TOWN_INTEGRAL_PN = TOWN_INTEGRAL_PN;
    }

    /**
     * get method 
     *
     * @return IECPAY.IP_REFUND_ORDER.TOWN_INTEGRAL_PN_AMT：null
     */
    public BigDecimal getTOWN_INTEGRAL_PN_AMT() {
        return TOWN_INTEGRAL_PN_AMT;
    }

    /**
     * set method 
     *
     * @param TOWN_INTEGRAL_PN_AMT  null
     */
    public void setTOWN_INTEGRAL_PN_AMT(BigDecimal TOWN_INTEGRAL_PN_AMT) {
        this.TOWN_INTEGRAL_PN_AMT = TOWN_INTEGRAL_PN_AMT;
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Ip_refund_order other = (Ip_refund_order) that;
        return (this.getORDER_ID() == null ? other.getORDER_ID() == null : this.getORDER_ID().equals(other.getORDER_ID()))
            && (this.getAC_DT() == null ? other.getAC_DT() == null : this.getAC_DT().equals(other.getAC_DT()))
            && (this.getAC_TM() == null ? other.getAC_TM() == null : this.getAC_TM().equals(other.getAC_TM()))
            && (this.getORN_ORDER_ID() == null ? other.getORN_ORDER_ID() == null : this.getORN_ORDER_ID().equals(other.getORN_ORDER_ID()))
            && (this.getMERC_ID() == null ? other.getMERC_ID() == null : this.getMERC_ID().equals(other.getMERC_ID()))
            && (this.getMERC_NAME() == null ? other.getMERC_NAME() == null : this.getMERC_NAME().equals(other.getMERC_NAME()))
            && (this.getREFUND_AMT() == null ? other.getREFUND_AMT() == null : this.getREFUND_AMT().equals(other.getREFUND_AMT()))
            && (this.getREFUNDP_ROCESS() == null ? other.getREFUNDP_ROCESS() == null : this.getREFUNDP_ROCESS().equals(other.getREFUNDP_ROCESS()))
            && (this.getCHECK_STATE() == null ? other.getCHECK_STATE() == null : this.getCHECK_STATE().equals(other.getCHECK_STATE()))
            && (this.getCHECK_DT() == null ? other.getCHECK_DT() == null : this.getCHECK_DT().equals(other.getCHECK_DT()))
            && (this.getPAY_LOG_NO() == null ? other.getPAY_LOG_NO() == null : this.getPAY_LOG_NO().equals(other.getPAY_LOG_NO()))
            && (this.getOPERATOR_ID() == null ? other.getOPERATOR_ID() == null : this.getOPERATOR_ID().equals(other.getOPERATOR_ID()))
            && (this.getOPERATOR_NAME() == null ? other.getOPERATOR_NAME() == null : this.getOPERATOR_NAME().equals(other.getOPERATOR_NAME()))
            && (this.getOPERATOR_TIME() == null ? other.getOPERATOR_TIME() == null : this.getOPERATOR_TIME().equals(other.getOPERATOR_TIME()))
            && (this.getMEMBER_ID() == null ? other.getMEMBER_ID() == null : this.getMEMBER_ID().equals(other.getMEMBER_ID()))
            && (this.getMEMBER_NAME() == null ? other.getMEMBER_NAME() == null : this.getMEMBER_NAME().equals(other.getMEMBER_NAME()))
            && (this.getREQUEST_TIME() == null ? other.getREQUEST_TIME() == null : this.getREQUEST_TIME().equals(other.getREQUEST_TIME()))
            && (this.getREMARK() == null ? other.getREMARK() == null : this.getREMARK().equals(other.getREMARK()))
            && (this.getGENERAL_INTEGRAL() == null ? other.getGENERAL_INTEGRAL() == null : this.getGENERAL_INTEGRAL().equals(other.getGENERAL_INTEGRAL()))
            && (this.getGENERAL_INTEGRAL_AMT() == null ? other.getGENERAL_INTEGRAL_AMT() == null : this.getGENERAL_INTEGRAL_AMT().equals(other.getGENERAL_INTEGRAL_AMT()))
            && (this.getPAY_TYPE() == null ? other.getPAY_TYPE() == null : this.getPAY_TYPE().equals(other.getPAY_TYPE()))
            && (this.getRED_PACKET_AMT() == null ? other.getRED_PACKET_AMT() == null : this.getRED_PACKET_AMT().equals(other.getRED_PACKET_AMT()))
            && (this.getGUEST_INTEGRAL() == null ? other.getGUEST_INTEGRAL() == null : this.getGUEST_INTEGRAL().equals(other.getGUEST_INTEGRAL()))
            && (this.getGUEST_INTEGRAL_AMT() == null ? other.getGUEST_INTEGRAL_AMT() == null : this.getGUEST_INTEGRAL_AMT().equals(other.getGUEST_INTEGRAL_AMT()))
            && (this.getTOWN_INTEGRAL_XA() == null ? other.getTOWN_INTEGRAL_XA() == null : this.getTOWN_INTEGRAL_XA().equals(other.getTOWN_INTEGRAL_XA()))
            && (this.getTOWN_INTEGRAL_TX_AMT() == null ? other.getTOWN_INTEGRAL_TX_AMT() == null : this.getTOWN_INTEGRAL_TX_AMT().equals(other.getTOWN_INTEGRAL_TX_AMT()))
            && (this.getTOWN_INTEGRAL_HX() == null ? other.getTOWN_INTEGRAL_HX() == null : this.getTOWN_INTEGRAL_HX().equals(other.getTOWN_INTEGRAL_HX()))
            && (this.getTOWN_INTEGRAL_XA_AMT() == null ? other.getTOWN_INTEGRAL_XA_AMT() == null : this.getTOWN_INTEGRAL_XA_AMT().equals(other.getTOWN_INTEGRAL_XA_AMT()))
            && (this.getTOWN_INTEGRAL_TX() == null ? other.getTOWN_INTEGRAL_TX() == null : this.getTOWN_INTEGRAL_TX().equals(other.getTOWN_INTEGRAL_TX()))
            && (this.getTOWN_INTEGRAL_HX_AMT() == null ? other.getTOWN_INTEGRAL_HX_AMT() == null : this.getTOWN_INTEGRAL_HX_AMT().equals(other.getTOWN_INTEGRAL_HX_AMT()))
            && (this.getTOWN_INTEGRAL_RX() == null ? other.getTOWN_INTEGRAL_RX() == null : this.getTOWN_INTEGRAL_RX().equals(other.getTOWN_INTEGRAL_RX()))
            && (this.getTOWN_INTEGRAL_RX_AMT() == null ? other.getTOWN_INTEGRAL_RX_AMT() == null : this.getTOWN_INTEGRAL_RX_AMT().equals(other.getTOWN_INTEGRAL_RX_AMT()))
            && (this.getTOWN_INTEGRAL_BA() == null ? other.getTOWN_INTEGRAL_BA() == null : this.getTOWN_INTEGRAL_BA().equals(other.getTOWN_INTEGRAL_BA()))
            && (this.getTOWN_INTEGRAL_BA_AMT() == null ? other.getTOWN_INTEGRAL_BA_AMT() == null : this.getTOWN_INTEGRAL_BA_AMT().equals(other.getTOWN_INTEGRAL_BA_AMT()))
            && (this.getTOWN_INTEGRAL_GP() == null ? other.getTOWN_INTEGRAL_GP() == null : this.getTOWN_INTEGRAL_GP().equals(other.getTOWN_INTEGRAL_GP()))
            && (this.getTOWN_INTEGRAL_GP_AMT() == null ? other.getTOWN_INTEGRAL_GP_AMT() == null : this.getTOWN_INTEGRAL_GP_AMT().equals(other.getTOWN_INTEGRAL_GP_AMT()))
            && (this.getTOWN_INTEGRAL_PN() == null ? other.getTOWN_INTEGRAL_PN() == null : this.getTOWN_INTEGRAL_PN().equals(other.getTOWN_INTEGRAL_PN()))
            && (this.getTOWN_INTEGRAL_PN_AMT() == null ? other.getTOWN_INTEGRAL_PN_AMT() == null : this.getTOWN_INTEGRAL_PN_AMT().equals(other.getTOWN_INTEGRAL_PN_AMT()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getORDER_ID() == null) ? 0 : getORDER_ID().hashCode());
        result = prime * result + ((getAC_DT() == null) ? 0 : getAC_DT().hashCode());
        result = prime * result + ((getAC_TM() == null) ? 0 : getAC_TM().hashCode());
        result = prime * result + ((getORN_ORDER_ID() == null) ? 0 : getORN_ORDER_ID().hashCode());
        result = prime * result + ((getMERC_ID() == null) ? 0 : getMERC_ID().hashCode());
        result = prime * result + ((getMERC_NAME() == null) ? 0 : getMERC_NAME().hashCode());
        result = prime * result + ((getREFUND_AMT() == null) ? 0 : getREFUND_AMT().hashCode());
        result = prime * result + ((getREFUNDP_ROCESS() == null) ? 0 : getREFUNDP_ROCESS().hashCode());
        result = prime * result + ((getCHECK_STATE() == null) ? 0 : getCHECK_STATE().hashCode());
        result = prime * result + ((getCHECK_DT() == null) ? 0 : getCHECK_DT().hashCode());
        result = prime * result + ((getPAY_LOG_NO() == null) ? 0 : getPAY_LOG_NO().hashCode());
        result = prime * result + ((getOPERATOR_ID() == null) ? 0 : getOPERATOR_ID().hashCode());
        result = prime * result + ((getOPERATOR_NAME() == null) ? 0 : getOPERATOR_NAME().hashCode());
        result = prime * result + ((getOPERATOR_TIME() == null) ? 0 : getOPERATOR_TIME().hashCode());
        result = prime * result + ((getMEMBER_ID() == null) ? 0 : getMEMBER_ID().hashCode());
        result = prime * result + ((getMEMBER_NAME() == null) ? 0 : getMEMBER_NAME().hashCode());
        result = prime * result + ((getREQUEST_TIME() == null) ? 0 : getREQUEST_TIME().hashCode());
        result = prime * result + ((getREMARK() == null) ? 0 : getREMARK().hashCode());
        result = prime * result + ((getGENERAL_INTEGRAL() == null) ? 0 : getGENERAL_INTEGRAL().hashCode());
        result = prime * result + ((getGENERAL_INTEGRAL_AMT() == null) ? 0 : getGENERAL_INTEGRAL_AMT().hashCode());
        result = prime * result + ((getPAY_TYPE() == null) ? 0 : getPAY_TYPE().hashCode());
        result = prime * result + ((getRED_PACKET_AMT() == null) ? 0 : getRED_PACKET_AMT().hashCode());
        result = prime * result + ((getGUEST_INTEGRAL() == null) ? 0 : getGUEST_INTEGRAL().hashCode());
        result = prime * result + ((getGUEST_INTEGRAL_AMT() == null) ? 0 : getGUEST_INTEGRAL_AMT().hashCode());
        result = prime * result + ((getTOWN_INTEGRAL_XA() == null) ? 0 : getTOWN_INTEGRAL_XA().hashCode());
        result = prime * result + ((getTOWN_INTEGRAL_TX_AMT() == null) ? 0 : getTOWN_INTEGRAL_TX_AMT().hashCode());
        result = prime * result + ((getTOWN_INTEGRAL_HX() == null) ? 0 : getTOWN_INTEGRAL_HX().hashCode());
        result = prime * result + ((getTOWN_INTEGRAL_XA_AMT() == null) ? 0 : getTOWN_INTEGRAL_XA_AMT().hashCode());
        result = prime * result + ((getTOWN_INTEGRAL_TX() == null) ? 0 : getTOWN_INTEGRAL_TX().hashCode());
        result = prime * result + ((getTOWN_INTEGRAL_HX_AMT() == null) ? 0 : getTOWN_INTEGRAL_HX_AMT().hashCode());
        result = prime * result + ((getTOWN_INTEGRAL_RX() == null) ? 0 : getTOWN_INTEGRAL_RX().hashCode());
        result = prime * result + ((getTOWN_INTEGRAL_RX_AMT() == null) ? 0 : getTOWN_INTEGRAL_RX_AMT().hashCode());
        result = prime * result + ((getTOWN_INTEGRAL_BA() == null) ? 0 : getTOWN_INTEGRAL_BA().hashCode());
        result = prime * result + ((getTOWN_INTEGRAL_BA_AMT() == null) ? 0 : getTOWN_INTEGRAL_BA_AMT().hashCode());
        result = prime * result + ((getTOWN_INTEGRAL_GP() == null) ? 0 : getTOWN_INTEGRAL_GP().hashCode());
        result = prime * result + ((getTOWN_INTEGRAL_GP_AMT() == null) ? 0 : getTOWN_INTEGRAL_GP_AMT().hashCode());
        result = prime * result + ((getTOWN_INTEGRAL_PN() == null) ? 0 : getTOWN_INTEGRAL_PN().hashCode());
        result = prime * result + ((getTOWN_INTEGRAL_PN_AMT() == null) ? 0 : getTOWN_INTEGRAL_PN_AMT().hashCode());
        return result;
    }
}